{
  "openapi": "3.0.0",
  "info": {
    "title": "PwnedAPI",
    "contact": {},
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://api.pwnedhub.com",
      "variables": {}
    }
  ],
  "paths": {
    "/access-token": {
      "post": {
        "tags": [
          "Misc"
        ],
        "summary": "Token Create (Login)",
        "operationId": "TokenCreate(Login)",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TokenCreateLoginRequest"
              },
              "example": {
                "username": "",
                "password": ""
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "delete": {
        "tags": [
          "Misc"
        ],
        "summary": "Token Delete (Logout)",
        "operationId": "TokenDelete(Logout)",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/users": {
      "get": {
        "tags": [
          "Misc"
        ],
        "summary": "Users Read",
        "operationId": "UsersRead",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "post": {
        "tags": [
          "Misc"
        ],
        "summary": "User Create (Register)",
        "operationId": "UserCreate(Register)",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserCreateRegisterRequest"
              },
              "example": {
                "username": "tim",
                "email": "tjt1980@gmail.com",
                "name": "Tim",
                "avatar": "https://www.gravatar.com/avatar/0a6d9b1ad59ad436bf9d9d16b2a7133e.png?s=300",
                "signature": "This is my signature.",
                "password": "password"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/users/5": {
      "get": {
        "tags": [
          "Misc"
        ],
        "summary": "User Read",
        "operationId": "UserRead",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "patch": {
        "tags": [
          "Misc"
        ],
        "summary": "User Update",
        "operationId": "UserUpdate",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserUpdateRequest"
              },
              "example": {
                "username": "tim",
                "email": "tjt1980@gmail.com",
                "name": "Tim",
                "avatar": "https://www.gravatar.com/avatar/0a6d9b1ad59ad436bf9d9d16b2a7133e.png?s=300",
                "signature": "This is my signature."
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/admin/users/5": {
      "patch": {
        "tags": [
          "Misc"
        ],
        "summary": "User Update (Admin)",
        "operationId": "UserUpdate(Admin)",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserUpdateAdminRequest"
              },
              "example": {
                "role": 0,
                "status": 1
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/password-reset": {
      "post": {
        "tags": [
          "Misc"
        ],
        "summary": "Password Reset Create",
        "operationId": "PasswordResetCreate",
        "parameters": [
          {
            "name": "Origin",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "http://test.pwnedhub.com"
            }
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PasswordResetCreateRequest"
              },
              "example": {
                "credential": "tim"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/users/5/password": {
      "put": {
        "tags": [
          "Misc"
        ],
        "summary": "Password Update (Profile)",
        "operationId": "PasswordUpdate(Profile)",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PasswordUpdateProfileRequest"
              },
              "example": {
                "new_password": "newpassword",
                "current_password": "password"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/notes": {
      "get": {
        "tags": [
          "Misc"
        ],
        "summary": "Note Read",
        "operationId": "NoteRead",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "put": {
        "tags": [
          "Misc"
        ],
        "summary": "Note Update",
        "operationId": "NoteUpdate",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/NoteUpdateRequest"
              },
              "example": {
                "content": "##### Welcome to PwnedHub 2.0!\n\nA collaborative space to conduct hosted security assessments.\n\n**Find flaws.**\n\n* This is your notes space. Keep your personal notes here.\n* Leverage popular security testing tools right from your browser in the tools space.\n\n**Collaborate.**\n\n* Privately collborate with coworkers in the messaging space.\n* Join public rooms in the messaging space to share information and socialize.\n\n**On the Move**\n\n* PwnedHub 2.0 is built with mobility in mind. No need for a separate app!\n\nHappy hunting!\n\n\\- The PwnedHub Team\n\n"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/rooms": {
      "get": {
        "tags": [
          "Misc"
        ],
        "summary": "Rooms Read",
        "operationId": "RoomsRead",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "post": {
        "tags": [
          "Misc"
        ],
        "summary": "Room Create",
        "operationId": "RoomCreate",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RoomCreateRequest"
              },
              "example": {
                "name": "1:5",
                "private": true,
                "members": [
                  1,
                  5
                ]
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/rooms/1/messages": {
      "get": {
        "tags": [
          "Misc"
        ],
        "summary": "Room Messages Read",
        "operationId": "RoomMessagesRead",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/unfurl": {
      "post": {
        "tags": [
          "Misc"
        ],
        "summary": "Unfurl Create",
        "operationId": "UnfurlCreate",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UnfurlCreateRequest"
              },
              "example": {
                "url": "https://www.slack.com"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/tools": {
      "get": {
        "tags": [
          "Misc"
        ],
        "summary": "Tools Read",
        "operationId": "ToolsRead",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "post": {
        "tags": [
          "Misc"
        ],
        "summary": "Tool Create",
        "operationId": "ToolCreate",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ToolCreateRequest"
              },
              "example": {
                "name": "ID",
                "path": "id",
                "description": "Displays the user ID of the current shell user."
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/tools/1": {
      "get": {
        "tags": [
          "Misc"
        ],
        "summary": "Tool Read",
        "operationId": "ToolRead",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "delete": {
        "tags": [
          "Misc"
        ],
        "summary": "Tool Delete",
        "operationId": "ToolDelete",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/scans": {
      "get": {
        "tags": [
          "Misc"
        ],
        "summary": "Scans Read",
        "operationId": "ScansRead",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "post": {
        "tags": [
          "Misc"
        ],
        "summary": "Scan Create",
        "operationId": "ScanCreate",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ScanCreateRequest"
              },
              "example": {
                "tid": 1,
                "args": "www.practisec.com"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/scans/d37b3139-5f74-4f00-81ff-5a1db7528f8b": {
      "delete": {
        "tags": [
          "Misc"
        ],
        "summary": "Scan Delete",
        "operationId": "ScanDelete",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/scans/d37b3139-5f74-4f00-81ff-5a1db7528f8b/results": {
      "get": {
        "tags": [
          "Misc"
        ],
        "summary": "Scan Results Read",
        "operationId": "ScanResultsRead",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/messages": {
      "get": {
        "tags": [
          "Misc"
        ],
        "summary": "Messages Read",
        "operationId": "MessagesRead",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "post": {
        "tags": [
          "Misc"
        ],
        "summary": "Message Create",
        "operationId": "MessageCreate",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/MessageCreateRequest"
              },
              "example": {
                "comment": "Hello everyone!",
                "room_id": 1
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/messages/11": {
      "get": {
        "tags": [
          "Misc"
        ],
        "summary": "Message Read",
        "operationId": "MessageRead",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "delete": {
        "tags": [
          "Misc"
        ],
        "summary": "Message Delete",
        "operationId": "MessageDelete",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "TokenCreateLoginRequest": {
        "title": "TokenCreateLoginRequest",
        "required": [
          "username",
          "password"
        ],
        "type": "object",
        "properties": {
          "username": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "example": {
          "username": "",
          "password": ""
        }
      },
      "UserCreateRegisterRequest": {
        "title": "UserCreateRegisterRequest",
        "required": [
          "username",
          "email",
          "name",
          "avatar",
          "signature",
          "password"
        ],
        "type": "object",
        "properties": {
          "username": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "avatar": {
            "type": "string"
          },
          "signature": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "example": {
          "username": "tim",
          "email": "tjt1980@gmail.com",
          "name": "Tim",
          "avatar": "https://www.gravatar.com/avatar/0a6d9b1ad59ad436bf9d9d16b2a7133e.png?s=300",
          "signature": "This is my signature.",
          "password": "password"
        }
      },
      "UserUpdateRequest": {
        "title": "UserUpdateRequest",
        "required": [
          "username",
          "email",
          "name",
          "avatar",
          "signature"
        ],
        "type": "object",
        "properties": {
          "username": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "avatar": {
            "type": "string"
          },
          "signature": {
            "type": "string"
          }
        },
        "example": {
          "username": "tim",
          "email": "tjt1980@gmail.com",
          "name": "Tim",
          "avatar": "https://www.gravatar.com/avatar/0a6d9b1ad59ad436bf9d9d16b2a7133e.png?s=300",
          "signature": "This is my signature."
        }
      },
      "UserUpdateAdminRequest": {
        "title": "UserUpdateAdminRequest",
        "required": [
          "role",
          "status"
        ],
        "type": "object",
        "properties": {
          "role": {
            "type": "integer",
            "format": "int32"
          },
          "status": {
            "type": "integer",
            "format": "int32"
          }
        },
        "example": {
          "role": 0,
          "status": 1
        }
      },
      "PasswordResetCreateRequest": {
        "title": "PasswordResetCreateRequest",
        "required": [
          "credential"
        ],
        "type": "object",
        "properties": {
          "credential": {
            "type": "string"
          }
        },
        "example": {
          "credential": "tim"
        }
      },
      "PasswordUpdateProfileRequest": {
        "title": "PasswordUpdateProfileRequest",
        "required": [
          "new_password",
          "current_password"
        ],
        "type": "object",
        "properties": {
          "new_password": {
            "type": "string"
          },
          "current_password": {
            "type": "string"
          }
        },
        "example": {
          "new_password": "newpassword",
          "current_password": "password"
        }
      },
      "PasswordUpdateResetRequest": {
        "title": "PasswordUpdateResetRequest",
        "required": [
          "new_password",
          "token"
        ],
        "type": "object",
        "properties": {
          "new_password": {
            "type": "string"
          },
          "token": {
            "type": "string"
          }
        },
        "example": {
          "new_password": "newpassword",
          "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NTY2ODY2MDYsImlhdCI6MTY1NjYwMDIwNiwic3ViIjo1fQ.eh8uPzcaNcUzqXNdq2iznvtgy3zKBOaUlKpG_3O47N0"
        }
      },
      "NoteUpdateRequest": {
        "title": "NoteUpdateRequest",
        "required": [
          "content"
        ],
        "type": "object",
        "properties": {
          "content": {
            "type": "string"
          }
        },
        "example": {
          "content": "##### Welcome to PwnedHub 2.0!\n\nA collaborative space to conduct hosted security assessments.\n\n**Find flaws.**\n\n* This is your notes space. Keep your personal notes here.\n* Leverage popular security testing tools right from your browser in the tools space.\n\n**Collaborate.**\n\n* Privately collborate with coworkers in the messaging space.\n* Join public rooms in the messaging space to share information and socialize.\n\n**On the Move**\n\n* PwnedHub 2.0 is built with mobility in mind. No need for a separate app!\n\nHappy hunting!\n\n\\- The PwnedHub Team\n\n"
        }
      },
      "RoomCreateRequest": {
        "title": "RoomCreateRequest",
        "required": [
          "name",
          "private",
          "members"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "private": {
            "type": "boolean"
          },
          "members": {
            "type": "array",
            "items": {
              "type": "integer",
              "format": "int32"
            },
            "description": ""
          }
        },
        "example": {
          "name": "1:5",
          "private": true,
          "members": [
            1,
            5
          ]
        }
      },
      "UnfurlCreateRequest": {
        "title": "UnfurlCreateRequest",
        "required": [
          "url"
        ],
        "type": "object",
        "properties": {
          "url": {
            "type": "string"
          }
        },
        "example": {
          "url": "https://www.slack.com"
        }
      },
      "ToolCreateRequest": {
        "title": "ToolCreateRequest",
        "required": [
          "name",
          "path",
          "description"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "path": {
            "type": "string"
          },
          "description": {
            "type": "string"
          }
        },
        "example": {
          "name": "ID",
          "path": "id",
          "description": "Displays the user ID of the current shell user."
        }
      },
      "ScanCreateRequest": {
        "title": "ScanCreateRequest",
        "required": [
          "tid",
          "args"
        ],
        "type": "object",
        "properties": {
          "tid": {
            "type": "integer",
            "format": "int32"
          },
          "args": {
            "type": "string"
          }
        },
        "example": {
          "tid": 1,
          "args": "www.practisec.com"
        }
      },
      "MessageCreateRequest": {
        "title": "MessageCreateRequest",
        "required": [
          "comment",
          "room_id"
        ],
        "type": "object",
        "properties": {
          "comment": {
            "type": "string"
          },
          "room_id": {
            "type": "integer",
            "format": "int32"
          }
        },
        "example": {
          "comment": "Hello everyone!",
          "room_id": 1
        }
      }
    },
    "securitySchemes": {
      "bearer": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "security": [],
  "tags": [
    {
      "name": "Misc",
      "description": ""
    }
  ]
}